package ca.poffm.graphql.todo;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.Transactional;

import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

import ca.poffm.graphql.todo.model.Task;
import lombok.extern.java.Log;

/**
 * Loads example data on startup.
 * 
 * @author PoffM
 */
@Component
@Log
public class ExampleDataLoader implements ApplicationRunner {
  
  @PersistenceContext
  private EntityManager entityManager;
  
  /**
   * Load sample data.
   */
  @Transactional
  @Override
  public void run(ApplicationArguments args) throws Exception {
    log.info("Loading sample data.");
    for (int i = 1; i <= 10000; i++) {
      Task task = new Task();
      task.setName("name" + i);
      task.setDescription("description" + i);
      task.setAutoGeneratedExample(true);
      entityManager.persist(task);
    }
    log.info("Sample data loaded.");
  }
  
}
