package ca.poffm.graphql.todo.model;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import lombok.Data;

/**
 * A to-do task.
 * 
 * @author PoffM
 */
@Entity
@Data
public class Task implements JpaNode {

  @Id
  @GeneratedValue
  private Long id;

  @NotNull
  @Size(min = 1, message="Name cannot be blank.")
  private String name;

  private String description;

  private Date dueDate;

  @NotNull
  private Boolean done = false;

  @CreationTimestamp
  private Date created;

  @UpdateTimestamp
  private Date updated;

  @NotNull
  private Boolean autoGeneratedExample = false;

}
